---
- name: HAProxy edge service rollout
  hosts: edge_haproxy
  become: true
  vars:
    edge_haproxy_state: "{{ edge_haproxy_state | default('present') }}"
    edge_haproxy_purge_data: "{{ edge_haproxy_purge_data | default(false) }}"
  roles:
    - edge_haproxy
