---
- name: SoftEther P2P server rollout
  hosts: softether_p2ps
  become: true
  vars:
    softether_p2p_state: present
    softether_p2p_purge_data: false
  roles:
    - softether_p2p

- name: SoftEther P2P client rollout
  hosts: candidate_softether_p2ps
  become: true
  vars:
    softether_p2p_state: present
    softether_p2p_purge_data: false
  roles:
    - softether_p2p
